[package]
name = "mpris-lyrics"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A simple Linux CLI that displays synced lyrics from the MPRIS `xesam:asText` property"
repository = "https://codeberg.org/AMA147000/mpris-lyrics"
keywords = ["mpris", "lyrics", "lrc", "cli"]

[features]

[dependencies]
mpris = "2.1.0"
lrc = "0.2.0"
ratatui = "0.30.2"
crossterm = "0.29.0"
